language: node_js
sudo: false
dist: trusty
node_js:
  - '8.9.1'

services:
  - mongodb
  - redis-server

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
 
script:
  - ng build --prod
  - karma start karma.conf.js --single-run
  
before_script:
- npm install -g angular-cli
- npm install -g karma
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
