language: node_js
sudo: false
dist: trusty
node_js:
  - '8.9.1'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
- npm install -g angular-cli
- npm install -g karma
- ng build
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
